/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;

import Model.Encounter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author riddhivora
 */
public class Addnewencounter extends javax.swing.JPanel {

    /**
     * Creates new form Addnewencounter
     */
    private static ArrayList<Encounter> encounters;
    private static ArrayList<Encounter> encountersList;
    public Addnewencounter(ArrayList<Encounter> encounters, ArrayList<Encounter> encountersList) {
        initComponents();
        this.encounters = encounters;
        this.encountersList = encountersList;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbpulse = new javax.swing.JLabel();
        lbdateofvisit = new javax.swing.JLabel();
        txtbloodpressure = new javax.swing.JTextField();
        txttemperature = new javax.swing.JTextField();
        txtdateofvisit = new javax.swing.JTextField();
        txtpulse = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        lbbloodpressure = new javax.swing.JLabel();
        lbtemperature = new javax.swing.JLabel();
        btnBack4 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("ADD NEW ENCOUNTER ");

        lbpulse.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbpulse.setText("Pulse");

        lbdateofvisit.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbdateofvisit.setText("Date of Visit");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lbbloodpressure.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbbloodpressure.setText("Blood Pressure");

        lbtemperature.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbtemperature.setText("Temperature");

        btnBack4.setText("Back");
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbtemperature)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdateofvisit, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpulse, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbdateofvisit)
                            .addComponent(lbbloodpressure)
                            .addComponent(lbpulse)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtemperature))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbpulse)
                    .addComponent(txtpulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbbloodpressure)
                    .addComponent(txtbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdateofvisit)
                    .addComponent(txtdateofvisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String errorMsgTemp="";
        String errorMsgBP="";
        String errorMsgPulse="";
        String errorMsgVisit="";

        String errorMsg = checkAllDigits(txttemperature.getText(), "Temperature");

        if(errorMsg != null){
            errorMsgTemp = errorMsg + "\n";
        }
        else{
            errorMsg = checkFieldIsNotEmpty(txttemperature.getText(), "Temperature");
            if(errorMsg != null)
            errorMsgTemp = errorMsg+ "\n";
            else
            errorMsgTemp = "";
        }

        errorMsg = checkAllDigits(txtbloodpressure.getText(), "Blood Pressure");

        if(errorMsg != null){
            errorMsgBP = errorMsg + "\n";
        }
        else{
            errorMsg = checkFieldIsNotEmpty(txtbloodpressure.getText(), "Blood Pressure");
            if(errorMsg != null)
            errorMsgBP = errorMsg + "\n";
            else
            errorMsgBP = "";
        }

        errorMsg = checkAllDigits(txtpulse.getText(), "Pulse");

        if(errorMsg != null){
            errorMsgPulse = errorMsg + "\n";
        }
        else{
            errorMsg = checkFieldIsNotEmpty(txtpulse.getText(), "Pulse");
            if(errorMsg != null)
            errorMsgPulse = errorMsg + "\n";
            else
            errorMsgPulse = "";
        }

        errorMsg = checkDateFormat(txtdateofvisit.getText(), "Date of Visit");

        if(errorMsg != null){
            errorMsgVisit = errorMsg + "\n";
        }
        else{
            errorMsg = checkFieldIsNotEmpty(txtdateofvisit.getText(), "Date of Visit");
            if(errorMsg != null)
            errorMsgVisit = errorMsg + "\n";
            else
            errorMsgVisit = "";
        }

        String allErrors = errorMsgTemp + errorMsgBP + errorMsgPulse + errorMsgVisit;

        if(errorMsgTemp != "" || errorMsgBP != "" || errorMsgPulse != ""  || errorMsgVisit != "" ){
            JOptionPane.showMessageDialog(this, allErrors);
        }
        else {
            VitalSigns vs = new VitalSigns(Double.parseDouble(txttemperature.getText()) , Double.parseDouble(txtbloodpressure.getText()), Integer.parseInt(txtpulse.getText()));
            Date date = new Date();
            int encounterId = encountersList.size() +1;
            Encounter encounter = new Encounter(encounterId, vs, date);
            encounters.add(encounter);
            encountersList.add(encounter);
            JOptionPane.showMessageDialog(this, "Added new encounter record sucessfully!!");
            close();
        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btnBack4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbbloodpressure;
    private javax.swing.JLabel lbdateofvisit;
    private javax.swing.JLabel lbpulse;
    private javax.swing.JLabel lbtemperature;
    private javax.swing.JTextField txtbloodpressure;
    private javax.swing.JTextField txtdateofvisit;
    private javax.swing.JTextField txtpulse;
    private javax.swing.JTextField txttemperature;
    // End of variables declaration//GEN-END:variables
}
